---
trigger: none
pool:
  vmImage: windows-2019
variables:
  solutionPath: '**/*.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release
stages:
  - stage: BuildIntegrationTests
    displayName: Build integration tests
    jobs:
    - job: build
      steps:
      - task: NuGetToolInstaller@1
        displayName: Install NuGet
      - task: NuGetCommand@2
        displayName: Run NuGet restore
        inputs:
          command: restore
          restoreSolution: '**/*.sln'
          feedsToUse: select
          vstsFeed: fbaf94f7-2d40-410a-8a27-de142d8d2313/2d8c792e-c1ad-4a66-924d-5bc4fec5fca0
      - task: VSBuild@1
        displayName: Build solution
        inputs:
          solution: $(solutionPath)
          platform: $(buildPlatform)
          configuration: $(buildConfiguration)
      - task: VSTest@2
        displayName: Run unit tests
        inputs:
          testSelector: testAssemblies
          testAssemblyVer2: |
            **\*test*.dll
            !**\*Behaviour.dll
            !**\*TestAdapter.dll
            !**\obj\**
          searchFolder: $(System.DefaultWorkingDirectory)
      - task: CopyFiles@2
        displayName: Copy artifact
        inputs:
          SourceFolder: $(system.defaultworkingdirectory)
          Contents: '**\bin\$(BuildConfiguration)\**'
          TargetFolder: $(build.artifactstagingdirectory)
          CleanTargetFolder: true
          OverWrite: true          
      - task: PublishBuildArtifacts@1
        displayName: Publish artifact
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: _AutomatedTests
          publishLocation: Container